### ISSUE TITLE
FR Edit button

### ISSUE THREAD

**Issue by bonnebulle** [JustFxDev/SubtasksOnBoard#3]
Whaou, this plugin is very helpful
An Edit and Remove button should be helpful too
Thanks

**Comment by bonnebulle** [comment]
subtasklist.php
```php
<?php
    $subtasks = $this->helper->subtasklistHelper->subtasks($task['id']);
    if (sizeof($subtasks) > 0):
?>
    <table class="table-suboncard">
    <div class="dropdown-submenu-open_alt">
        <li>
            <a href="/?controller=SubtaskController&action=create&task_id=<?php print_r($task["id"]) ?>" class="js-modal-medium" title="add"><i class="fa fa-plus fa-fw" aria-hidden="true"></i></a>
        </li>
    </div>
    <?php foreach ($subtasks as $subtask): ?>
        <tr>
            <td>
                <?= $this->subtask->renderToggleStatus($task, $subtask) ?>
                <div class='edit_subtask'>
                <a class="js-modal-medium" href="/?controller=SubtaskController&action=edit&task_id=<?php print_r($task["id"]) ?>&subtask_id=<?php print_r($subtask["id"]) ?>">
                    <i class="fa fa-edit fa-fw js-modal-large" aria-hidden="true"></i></a>
                </a>
                </div>
            </td>
            <?= $this->hook->render('template:board:tooltip:subtasks:rows', array('subtask' => $subtask)) ?>
        </tr>
        <?php endforeach ?>
    </table>
    
<?php else: ?>

    <table class="table-suboncard">
        <div class="dropdown-submenu-open_alt">
            <li>
                <a href="/?controller=SubtaskController&action=create&task_id=<?php print_r($task["id"]) ?>" class="js-modal-medium" title="add"><i class="fa fa-plus fa-fw" aria-hidden="true"></i></a>
            </li>
        </div>    
    </table>

<?php endif ?>
```

/assets/js/app.js
```js
  $(document).on("click", ".dropdown-submenu-open_alt li a", function (e) {
      e.preventDefault();
      let url=$(this).attr("href")
      KB.modal.open(url, "medium", !0);
  });

```

... extra CSS
```css

.task-board div.edit_subtask {
  display: inline-block;
  float: right;
  clear: none;
  width: 25px;
  text-align: right;
  height: 21px;
  margin-top: 0px;
  padding-right: 5px;
  color: #5755d9;
}
.task-board div.edit_subtask a  {
 color: #5755d9;
}
.subtask-title {
  width: calc(100% - 29px) !important;
  display: inline-block;
}

.dropdown-submenu-open_alt {
  float: right;
  margin-top: -20px;
  position: relative;
  margin-right: -9px;
  margin-bottom: -7px;
}
```

Forked :
https://github.com/bonnebulle/SubtasksOnBoard_bonnebulle/
